### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by paternal** [texfaq/historical#1] opened 2018-06-13 09:33 UTC
The website https://www.tex.ac.uk/ is unreachable (I get a github 404 page). This looks like a error in the github pages configuration.

I am not sure how relevant this is, since this repo is marked as `historical`, but since it is still referenced on the internet ([example](https://en.wikipedia.org/wiki/LuaTeX#cite_ref-3)), it would be nice to keep it live.

Cross posted in uktug/uk-tex-faq#7, since I cannot figure which is the "official" repository.

-- Louis

**Comment by josephwright** [comment] 2018-06-13 09:48
Duplicate of https://github.com/uktug/uk-tex-faq/issues/7

**Comment by josephwright** [comment] 2018-06-13 09:49
Duplicate of https://github.com/uktug/uk-tex-faq/issues/7

**Comment by josephwright** [comment] 2018-06-13 09:49
Oops, wrong repo duped to: I thought you'd reported again the live data.

**Comment by josephwright** [comment] 2018-06-14 17:12
This is now fixed :)

**Closed as completed by josephwright** 2018-06-14 17:12 UTC
